### ISSUE TITLE
Python directory ethsnarks/ethsnarks as a PyPI package

### ISSUE THREAD

**Issue by wanseob** [HarryR/ethsnarks#155]
This python library is quite useful for zk-SNARKs, so it would be really good if I can use this lib with 
```
pip install ethsnarks
```
If you don't mind can I make it as a PyPI package? My plan is 
1. fork this repository
2. commit the subtree `ethsnarks/ethsnarks` 
3. Add some setup.py and make it as PyPI package
4. Transfer ownership back to HarryR

**Comment by HarryR** [comment]
This sounds good. Say we call it `ethsnarks-python` ?

However, I think it would be best if we can switch the `ethsnarks` directory in the main (this) repository with a git submodule.

Most of the tests don't depend on any of the native code, but there are some which do - I guess those can be excluded from a Python-only repository?

Would this layout work: So you can use the main ethsnarks directory in `PYTHONPATH` so it doesn't break compatibility with existing projects?

* `ethsnarks`
  * `ethsnarks` -> ethsnarks-python git submodule (contians python package, `__init__.py` etc.)

Or would something like this be necessary, to make it compatible with PyPi and installable via pip from a GitHub url etc.

 * `ethsnarks`
    * `python` -> ethsnarks-python git submodule
       * `ethsnarks` (contains python package, `__init__.py` etc.)

**Comment by wanseob** [comment]
The first idea looks good!
- `ethsnarks`
  - `ethsnarks`: https://github.com/harryR/ethsnarks-python git submodule

**Comment by wanseob** [comment]
Rather than creating a new separate repository, adding `setup.py` like `truffle.js` simply solves this issue. Please check my PR #157
