### ISSUE TITLE
Question about the MiMC implementation

### ISSUE THREAD

**Issue by arnaucube** [HarryR/ethsnarks#161]
In the [MiMC_hash.sol line 27](https://github.com/HarryR/ethsnarks/blob/master/contracts/MiMC_hash.sol#L27), is doing `r = ( r + in_x[i] ) + hash(in_x[i], r) mod q`.
Looking to the MiMC paper https://eprint.iacr.org/2016/492.pdf at page 5 seems that is doing `r = r + hash(in_x[i], r) mod q`.
Why is the implementation adding `( r + in_x[i] )` to the output of the hash in each iteration of the loop?
I don't know if I'm missing/missunderstanding something

**Comment by HarryR** [comment]
This is the Preneel one-way compression function using the MiMC keyed permutation, to turn it into a hash rather than a cipher.

See: https://en.wikipedia.org/wiki/One-way_compression_function

**Comment by arnaucube** [comment]
Great! Thank you :relaxed:
