### ISSUE TITLE
Safe Add and Safe Subtract

### ISSUE THREAD

**Issue by HarryR** [HarryR/ethsnarks#62]
For many applications there's a need for a safe add and safe subtract.

This should be an N bit number with overflow protection.

This is related to #64

**Comment by HarryR** [comment]
The other option is having a 'safe subtract N from A then add N to B' gadget, used to perform a transfer of value from one person to another (or to accumulate the fees).

    c = A-N
    d = B+N

This would require two gadgets, one to verify that `N>=A` and one to ensure that `B+N != overflow`, but is there any cheaper way of doing this?

When adding two `N` bit numbers, the result will be at most a `N+1` bit number. If the MSB of the `N+1` bit number is 1, then there has been an overflow. However, this requires an additional `N+2` constraints to sum the result then convert back into bits, then ensure that the highest bit is zero.

The easiest way to implement overflow detection is to implement a full adder which only outputs the carry flag as a 3-bit lookup table. Where if the final output (carry bit) is 1 then there's been an overflow. This requires `2*N` constraints for two `N` bit numbers. (one for the 3bit window, one for the selector for each bit).

**Comment by HarryR** [comment]
Take two N bit numbers, A and B.

 * Verify `A` is `N` bits, via packer
 * Verify `B` is `N` bits, via packer
 * Verify `A+B == C`
 * Verify C is N+1 bits via packer
 * Ensure the `N+1`th bit is `0`

This requires the following constraints:

 * `N * bitness` for `A`
 * `N * bitness` for `B`
 * `pack(A_bits) = A`
 * `pack(B_bits) = B`
 * `A+B=C`
 * `N+1 * bitness` for `C`
 * `pack(C_bits) = C`
 * ensure `N+1`th bit of `C` is zero.

Which is `3*N + 1 + 5` constraints.

**Comment by barryWhiteHat** [comment]
Say we want to add a number a and b. We can require the witness to provide us with a_b , b_b which are binary representations of a and b. We can then pack them into a field elements. 

We know that a + b = c that c will be at most `max(len(a), len(b)) +1` bits. So if we make sure that c_b is less than 252 we don't need to worry about overflow. We can do that by ensuring that both a_b and b_b are less than 252 bits in length.
