### ISSUE TITLE
Build WASM prover / module

### ISSUE THREAD

**Issue by HarryR** [HarryR/ethsnarks#7]
For any of the SNARK circuits, we should be able to build a WebAssembly module which:

 * exports prove / verify functions
 * allows loading proving key from HTTP backend

This seems fairly straightforward, using the current cmake project, to build target webassembly using Emscriptem, without modifying any of the C++ code heavily.

References:

 * https://developers.google.com/web/updates/2018/03/emscripting-a-c-library
 * https://github.com/adevaykin/minimal-cmake-emscripten-project
 * https://stackoverflow.com/questions/37747205/cmake-project-for-emscripten#37869647
 * https://kripken.github.io/emscripten-site/docs/porting/files/index.html
 * https://kripken.github.io/emscripten-site/docs/porting/files/Synchronous-Virtual-XHR-Backed-File-System-Usage.html
 * http://forums.4fips.com/viewtopic.php?f=3&t=1201
 * https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html
 * http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html?highlight=optimisation
 * "Use llvm-lto when compiling from bitcode to JavaScript: --llvm-lto 1. This can break some code as the LTO code path is less tested."

This will need to be a separate repo which uses the `ethsnarks` repo as a sub-module.

**Comment by barryWhiteHat** [comment]
@Schaeff can you link to some of your work on this?

**Comment by HarryR** [comment]
So, I have a work-in-progress repo which uses Emscripten to build the `ethsnarks` repo (as well as libgmp, openssl & boost).

There are a few broken things though:

 * File IO doesn't seem to work well, `ios.is_open` is returning `false`
 * Memory limit is 2gb (signed 16 bit integer, upper bound 32767)

Executable sizes are very reasonable:

 * `hashpreimage_cli.js` - 234kb
 * `hashpreimage_cli.wasm` - 989kb
 * `miximus_genKeys.wasm` - 767kb
 * `verify.js` - 230kb
 * `verify.wasm` - 652kb

I'm going to add some more test executables to the repo which do end-to-end tests to see if I can get the SHA256-full circuit proving and then verifying under webassembly without reaching the memory limit.

Staying under the 2gb limit is gonna be ... challenging, especially with larger circuits, but it's doable.

**Comment by barryWhiteHat** [comment]
So cool! These tools are gonna be really useful.

**Comment by Schaeff** [comment]
Hi @HarryR sounds very cool, tagging @lucasvo who has been looking at similar things

**Comment by HarryR** [comment]
Only two modifications need making to `libsnark`:

 * in `basic_radix2_domain_aux.tcc` remove the empty `asm volatile` chunks. - they only contain a `/* pre-inner */` and `/* post-inner */` - Emscripten checks for empty asm() statements and ignores them, but doesn't consider comments.
 * in `profiling.cpp` in `get_nsec_cpu_time`, `clock_gettime` isn't supported, so need to add `if defined(_MSC_VER) || defined(__EMSCRIPTEN__) return 0;` rather than just `_MSC_VER`

However, the wasm build is *dog slow*.

Also in `Call to r1cs_to_qap_instance_map_with_evaluation` throws then catches a bunch of exceptions (for unknown reasons), but continues running.

I made a test which, in one go creates a mod_hashpreimage, creates keypair, proves something, then verifies the proof.

Time for test_hashpreimage native build:

 * generating proving key: 18.6s
 * generating proof: 4.4438s
 * verifying proof: 0.0419s

Times for test_hashpreimage WASM build:

 * generating proving key: 817s (48x slower)
 * generating proof: 216s (48x slower)
 * verifying proof: 1.8s (42x slower)

That'a significant decrease in speed... like very significant.

**Comment by HarryR** [comment]
After building GMP with 64bit limbs, cleaning up the `ethsnarks-emscripten` repository, and running the next set of tests, the results are:

 * generating proving key: 829s
 * generating proof: 205s
 * verifying proof: 1.5s

It doesn't seem, for WASM, that there's much difference between 32bit limbs and 64bit limbs.

Anyway, all the stuff needed to build is at: https://github.com/HarryR/ethsnarks-emscripten
